name: managed

on:
  push:
    paths:
    - 'src/**'
  pull_request:
    paths:
    - 'src/**'

jobs:
  multi:
    uses: xoofx/.github/.github/workflows/dotnet-multi.yml@main
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
