name: native

on:
  push:
    paths:
    - 'ext/**'
  pull_request:
    paths:
    - 'ext/**'

defaults:
  run:
    working-directory: ext

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt-get install gcc-aarch64-linux-gnu
          sudo apt-get install g++-aarch64-linux-gnu
          sudo apt-get install gcc-arm-linux-gnueabihf
          sudo apt-get install g++-arm-linux-gnueabihf
    - name: Build
      run: |
          ./build_monocypher_native.ps1
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: monocypher-native-${{ matrix.os }}
        path: ext/build/package